[package]
name = "caro-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
bson = "2.3"
rusqlite = { version = "0.28", features = ["bundled"] }
serde = "1.0"

[dev-dependencies]
tempdir = "0.3.7"
