[package]
name = "karo-storage"
version = "0.1.0"
edition = "2021"

[dependencies]
bson = "2.3"
serde = "1.0"

karo-storage-common = { path = "../karo-storage-common" }

[dev-dependencies]
tempdir = "0.3.7"
