[package]
name = "karo-storage-viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
bson = "2.3"
clap = { version = "3.2", features = ["derive", "color"] }
colored = "2.0.0"

karo-storage-common = { path = "../karo-storage-common" }
